service: api-scrapper-service
app: api-scrapper
tenant: amanneox
provider:
  name: aws
  stage: dev
  region: ap-south-1
  runtime: nodejs8.10

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: user
          method: post
          cors: true

  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: user/{id}
          method: put
          cors: true

  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true

  user:
    handler: handler.user
    events:
      - http:
          path: user/{id}
          method: get
          cors: true

  zomato-getCategories:
    handler: handlers/zomato/extract.getCategories
    events:
      - http:
          path: zomato/getCategories
          method: get
          cors: true

  zomato-getCity:
    handler: handlers/zomato/extract.getCity
    events:
      - http:
          path: zomato/getCity
          method: post
          cors: true
