service: api-scrapper-zomato-service
app: api-scrapper
tenant: amanneox
provider:
  name: aws
  stage: dev
  region: ap-south-1
  runtime: nodejs8.10

functions:
  zomato-getCategories:
    handler: handlers/zomato/extract.getCategories
    events:
      - http:
          path: zomato/getCategories
          method: get
          cors: true

  zomato-getCity:
    handler: handlers/zomato/extract.getCity
    events:
      - http:
          path: zomato/getCity
          method: post
          cors: true
